[project]
name = "translater"
version = "0.1.0"
description = "A python module"
readme = "README.md"
authors = [
  { name = "Nathan Nichols", email = "communications@resultsmotivated.com" },
]

[project.scripts]
# Makes 'spam-cli' an executable on PATH
ebook-translate = "translater.cli:run0"

[tool.poetry]
version = "2.1.1"

[tool.poetry.dependencies]
python = ">=3.10,<4"
loguru = "^0.7.3"
readabilipy = "^0.3.0"
translatehtml = "^1.5.2"
argostranslate = "^1.9.6"
ebooklib = "^0.18"
rich-click = "^1.8.8"
dataclass-click = "^1.0.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8"
black = "^24.4.2"

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["translater",]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    "ignore:.*unclosed.*:ResourceWarning",
]